trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - prod/base-infra
    exclude:
      - README.md
      - CHANGELOG.md
      - Makefile

resources:
  repositories:
    - repository: default
      type: git
      name: microservice-theworld

variables:
  - group: common-vars
    
pool:
  vmImage: $(POOL_IMAGE)

stages:
  - stage: main
    displayName: main
    jobs:
      - template: templates/job-aws-terraform-deploy.yml@default
        parameters:
          path: prod/base-infra
          jobName: Base_Infra_Prod
          awsConnection: AWS_CONNECTION
          environment: Base-Infra - Prod